### ISSUE TITLE
崩溃问题其实有解决方案

### ISSUE THREAD

**Issue by chiwei233** [sieveLau/RWSimplifiedPatcher#2]
很多人用RimTrans都崩溃，可以参考以下指南：
https://steamcommunity.com/sharedfiles/filedetails/?id=2305706684

**Comment by sieveLau** [comment]
最近没有怎么玩了，但是上次用这个patch生成器的时候还能汉化1.3的mod，除了不会像rimtrans那样自动引用已有的汉化词之外没啥不好。就暂时先这样。
